#ifndef AR_ASSETPATHRESOLVER_API_H
#define AR_ASSETPATHRESOLVER_API_H

#include "pxr/base/arch/export.h"

#if defined(ASSETPATHRESOLVER_EXPORTS)
#   define AR_ASSETPATHRESOLVER_API ARCH_EXPORT
#else
#   define AR_ASSETPATHRESOLVER_API ARCH_IMPORT
#endif

#endif // AR_ASSETPATHRESOLVER_API_H
