#ifndef AR_ASSETPATHRESOLVER_DEBUG_CODES_H
#define AR_ASSETPATHRESOLVER_DEBUG_CODES_H

#include "pxr/pxr.h"
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    ASSETPATHRESOLVER_RESOLVER
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // AR_ASSETPATHRESOLVER_DEBUG_CODES_H
